export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary':   '#0F172A',
        'bg-card':      '#1E293B',
        'bg-secondary': '#273449',
        'brand':        '#8B5CF6',
        'brand-dark':   '#7C3AED',
        'interactive':  '#38BDF8',
        'success':      '#10B981',
        'gold':         '#FBBF24',
        'danger':       '#EF4444',
        'text-primary': '#E6EDF7',
        'text-muted':   '#A8B3C7',
        'rank-beginner':'#64748B',
        'rank-bronze':  '#B87333',
        'rank-silver':  '#C0C0C0',
        'rank-gold':    '#FBBF24',
      },
      fontFamily: { sans: ['Inter', 'system-ui', 'sans-serif'] },
      animation: {
        'shimmer':    'shimmer 1.5s infinite',
        'float-up':   'floatUp 1.5s ease-out forwards',
        'fade-in':    'fadeIn 0.25s ease-out',
        'slide-in':   'slideIn 0.3s ease-out',
        'bounce-xp':  'bounceXP 0.6s ease-out',
        'spin-slow':  'spin 3s linear infinite',
        'pulse-ring': 'pulseRing 2s ease-in-out infinite',
      },
      keyframes: {
        shimmer:   { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
        floatUp:   { '0%': { opacity: '1', transform: 'translateY(0)' }, '100%': { opacity: '0', transform: 'translateY(-70px)' } },
        fadeIn:    { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideIn:   { from: { opacity: '0', transform: 'translateX(50px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        bounceXP:  { '0%,100%': { transform: 'scale(1)' }, '40%': { transform: 'scale(1.3)' }, '70%': { transform: 'scale(0.95)' } },
        pulseRing: { '0%,100%': { boxShadow: '0 0 0 0 rgba(139,92,246,0.4)' }, '50%': { boxShadow: '0 0 0 8px rgba(139,92,246,0)' } },
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, #8B5CF6, #38BDF8)',
        'gold-gradient':  'linear-gradient(135deg, #8B5CF6, #FBBF24)',
        'hero-grid':      'radial-gradient(circle at 1px 1px, rgba(139,92,246,0.07) 1px, transparent 0)',
      },
      backgroundSize: { grid: '40px 40px' },
      boxShadow: {
        'brand': '0 0 24px rgba(139,92,246,0.3)',
        'card':  '0 4px 24px rgba(0,0,0,0.3)',
        'glow':  '0 0 40px rgba(139,92,246,0.15)',
      },
    },
  },
  plugins: [],
}
